category_urls:
  type: list
  default: |
    [
      {"name": "From the Team", "url": "https://community.rabbit.tech/c/from-the-team/11"},
      {"name": "All Things Rabbit", "url": "https://community.rabbit.tech/c/all-things-rabbit/5"},
      {"name": "LAM, Teach Mode & Agents", "url": "https://community.rabbit.tech/c/developer-discussion/14"},
      {"name": "The World of AI", "url": "https://community.rabbit.tech/c/all-things-ai/6"},
      {"name": "Issues & Bugs", "url": "https://community.rabbit.tech/c/help-and-bug-reports/7"},
      {"name": "Suggestions & Ideas", "url": "https://community.rabbit.tech/c/suggestions-ideas/10"},
      {"name": "Community & Events", "url": "https://community.rabbit.tech/c/community-events/12"},
      {"name": "General Chat", "url": "https://community.rabbit.tech/c/general/4"}
    ]
  description: "List of category URLs and names."

category_images:
  type: upload
  list: true
  description: "Upload banner images for each category in order."
