rabbit_banners:
  type: list
  default: |
    [
      {"title": "From the Team", "url": "https://community.rabbit.tech/c/from-the-team/11", "image_url": "https://cdck-file-uploads-global.s3.dualstack.us-west-2.amazonaws.com/flex002/uploads/rabbit/original/2X/c/c738ac09900d3d6b406a4dabb25af2db93204c8a.jpg"},
      {"title": "All Things Rabbit", "url": "https://community.rabbit.tech/c/all-things-rabbit/5", "image_url": "https://cdck-file-uploads-global.s3.dualstack.us-west-2.amazonaws.com/flex002/uploads/rabbit/original/2X/c/c738ac09900d3d6b406a4dabb25af2db93204c8a.jpg"},
      {"title": "LAM, Teach Mode & Agents", "url": "https://community.rabbit.tech/c/developer-discussion/14", "image_url": "https://cdck-file-uploads-global.s3.dualstack.us-west-2.amazonaws.com/flex002/uploads/rabbit/original/2X/c/c738ac09900d3d6b406a4dabb25af2db93204c8a.jpg"}
    ]
